import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "../providers/ConvexClientProvider";
import { Toaster } from "sonner";
import { QueryProvider } from "@/providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-theme-bg`}
      >
        <ConvexClientProvider>
          <QueryProvider>
            {children}
            <Toaster
              theme="dark"
              position="top-right"
              richColors
              toastOptions={{
                style: {
                  background: "#363136",
                  border: "1px solid #4a4a4a",
                  color: "#e5e5e5",
                },
              }}
            />
          </QueryProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
